version: "3.9"

services:
  bots:
    build: ./
    ports:
      - 80:8000
    restart: always
    volumes:
      - ./app:/app/
    command: sh -c "uvicorn server:app --host 0.0.0.0 --reload --proxy-headers && gunicorn -k uvicorn.workers.UvicornWorker"
