name: Test Backend and Deploy

on:
   [push]

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          
          pip install poetry && poetry install --no-interaction --no-ansi
      - name: Linting with Mypy
        run: poetry run mypy ./app
      - name: Linting with Pylint
        run: poetry run pylint ./app
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: checking
    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PROJECT_FOLDER }}
            git switch main
            git pull
            docker compose up -d --build