name: Test Backend and Deploy

on:
   push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./bots
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Linting with Mypy
        working-directory: ./bots
        run: mypy .
      - name: Linting with Pylint
        working-directory: ./bots
        run: pylint .
      # - name: Test with pytest
      #   working-directory: ./backend
      #   run: |
      #     pytest .
  deploy-backend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PROJECT_FOLDER }}
            git switch main
            git pull
            docker compose up -d --build